# Generated by Django 5.2.5 on 2025-08-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_admin", "0001_admin_audit_log"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="admin_audit_action_0be5f6_idx",
            old_name="admin_audi_action_created_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="admin_audit_target__1b2cb0_idx",
            old_name="admin_audi_target_type_id_idx",
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("suspend", "Suspend Reseller"),
                    ("resume", "Resume Reseller"),
                    ("payout", "Process Payout"),
                    ("edit", "Edit Reseller"),
                    ("bulk", "Bulk Action"),
                    ("message", "Send Message"),
                    ("export", "Export Data"),
                ],
                max_length=32,
            ),
        ),
    ]
