# Generated by Django 5.2.5 on 2025-08-28 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "platform_admin",
            "0002_rename_admin_audi_action_created_idx_admin_audit_action_0be5f6_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("revenue_summary", "Revenue Summary"),
                            ("commission_report", "Commission Report"),
                            ("payout_report", "Payout Report"),
                            ("financial_overview", "Financial Overview"),
                            ("cash_flow_statement", "Cash Flow Statement"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                            ("csv", "CSV"),
                            ("html", "HTML"),
                        ],
                        default="pdf",
                        max_length=16,
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        help_text="Cron expression: m h dom mon dow", max_length=64
                    ),
                ),
                (
                    "recipients",
                    models.JSONField(
                        default=list, help_text="List of recipient email addresses"
                    ),
                ),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "admin_scheduled_reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
