# Generated by Django 5.2.5 on 2025-08-28 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_admin", "0003_scheduledreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("general", models.JSONField(blank=True, default=dict)),
                ("security", models.JSONField(blank=True, default=dict)),
                ("notifications", models.JSONField(blank=True, default=dict)),
                ("integrations", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Platform Settings",
                "verbose_name_plural": "Platform Settings",
            },
        ),
    ]

