# Generated by Django 4.2 on 2025-06-24 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_business'),
        ('App', '0003_alter_otp_purpose_userprofile'),
    ]

    operations = [
    ]
