# Generated by Django 5.2.1 on 2025-06-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_merge_20250624_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('business_owner', 'Business Owner'), ('reseller', 'Reseller'), ('pending', 'Pending Role')], default='pending', max_length=20),
        ),
    ]
