# Generated by Django 5.2.1 on 2025-07-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_plan_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('business_owner', 'Business Owner'), ('reseller', 'Reseller'), ('admin', 'Admin'), ('pending', 'Pending Role')], default='pending', max_length=20),
        ),
    ]
