# Generated by Django 5.1.6 on 2025-08-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('register', 'Register'), ('password_reset', 'Password Reset')], max_length=20),
        ),
    ]
