# Generated by Django 5.2.5 on 2025-08-27 14:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0009_alter_otp_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="business",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="business",
            name="business_email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
