# Generated by Django 5.2.5 on 2025-08-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0013_paymentrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrecord",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
