# Generated by Django 5.2.5 on 2025-08-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0014_paymentrecord_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrecord",
            name="billing",
            field=models.CharField(blank=True, default="monthly", max_length=20),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="payment_method",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="plan_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="provider_status",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
