# Generated by Django 5.1.6 on 2025-07-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseller',
            name='reseller_type',
            field=models.CharField(choices=[('individual', 'Individual Affiliate'), ('business', 'Business Partner')], default='individual', max_length=20),
        ),
        migrations.AlterField(
            model_name='reseller',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reseller',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
